# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14e54651861e84e23ef3d44b21480736baaaae84f4e4a6b9fd03be088e98c25491a18e3b8d31506994e62be34b54fdfb40a019f5cc11dfb30d9a1c61eff2211a

test:
  secret_key_base: 474703c408cffa40bbd1511dc913474fc2b5c86bb14cb49c3e75c38e401e85063b2548600072f31ae588018351ba03ed407d927d1410f8463a1df69b599daa18

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
